project:
  type: website
  output-dir: docs

website:
  title: "Igor Kuivjogi Fernandes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/igorkf/
      - icon: linkedin
        href: https://www.linkedin.com/in/igorkuivjogi/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

